- project:
    check:
      jobs:
        - dhall-diff:
            nodeset:
              nodes:
                - label: pod-dhall-1-33
                  name: pod-dhall-1-33
    gate:
      jobs:
        - dhall-diff:
            nodeset:
              nodes:
                - label: pod-dhall-1-33
                  name: pod-dhall-1-33
